name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - nodejs=18
  - jupyter_server
  - jupyterlab-night
  - jupyterlab-language-pack-fr-FR
  - jupyterlite-core >=0.4.0,<0.5.0
  - voici >=0.7.0,<0.8.0
